defaults:
  - task_config_base
  - actions:
    - stop
    - move_forward
    - turn_left
    - turn_right
  - measurements:
    - episode_length
    - distance_to_goal
    - success
    - spl
  - lab_sensors:
    - pin_goal_sensor
    - compass_sensor
    - gps_sensor
  - _self_

type: PIN-v1
end_on_success: True
reward_measure: "distance_to_goal_reward"
success_measure: "spl"
objects_path: "data/datasets/pin/hm3d/v1/objects"
include_distractors: True
exclude_cat_distractors: True

lab_sensors:
  pin_goal_sensor:
    object_images_path: "data/datasets/pin/hm3d/v1/object_images"
    W: 1280
    H: 960

measurements:
  distance_to_goal:
    distance_to: POINT
  success:
    success_distance: 1.0